# version: '3.8'  

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:9000"
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

  redis:
    image: redis 

volumes:
  db_data:  # Define the volume
